# Generated by Django 6.1 on 2026-09-07 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('captian', models.CharField(max_length=100)),
                ('mem1', models.CharField(max_length=100)),
                ('mem2', models.CharField(max_length=100)),
                ('mem3', models.CharField(max_length=100)),
                ('mem4', models.CharField(max_length=100)),
                ('mem5', models.CharField(max_length=100)),
                ('mem6', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('W', models.IntegerField(default=0)),
                ('L', models.IntegerField(default=0)),
                ('pts', models.IntegerField(default=0)),
                ('matches', models.IntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vbscores.team')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField()),
                ('team1_sets', models.IntegerField(blank=True, null=True)),
                ('team2_sets', models.IntegerField(blank=True, null=True)),
                ('mvp_name', models.CharField(blank=True, default='', max_length=100)),
                ('is_played', models.BooleanField(default=False)),
                ('played_at', models.DateTimeField(blank=True, null=True)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team1', to='vbscores.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team2', to='vbscores.team')),
            ],
        ),
    ]
